### ISSUE TITLE
why cost more memory than original 0.3 version

### ISSUE THREAD

**Issue by mingminzhen** [wandering007/efficient-densenet-pytorch#3]
hi, I used the pytorch 0.3 version from [https://github.com/gpleiss/efficient_densenet_pytorch](url). It seems the 0.3 version cost far less memory than your 0.4 version. Do you have tried to compare this?

**Comment by wandering007** [comment]
@mingminzhen It doesn't matter that my implementation uses more memory (in fact it is a improvement as it runs faster). The largest acceptable batch sizes of the two implementations  are comparable for a given maximal gpu memory capacity, you can check that.
